more cleanup before merging into develop

diff --git a/bin/stoke b/bin/stoke
--- a/bin/stoke
+++ b/bin/stoke
@@ -7,6 +7,12 @@ pushd `dirname $0` > /dev/null
 HERE=`pwd`
 popd > /dev/null
 
+if [ `ls -1 $HERE | wc -l` -ne "17" ]
+then
+	echo "Fatal Error: Failed to locate one or more STOKE components!"
+	exit 1
+fi
+
 if [ $# -eq 0 ] 
 then
 	echo "Type 'stoke --help' for usage."
@@ -25,8 +31,6 @@ then
 	echo "  replace             replace the contents of a binary file"
 	echo "  search              run STOKE search"
 	echo "  testcase            generate a STOKE testcase file"
-  echo "  database            modify or query a database of binaries"
-  echo "  test                run the test suite"
 	echo ""
 	echo "  debug cfg           generate the control flow graph for a function"
 	echo "  debug cost          evaluate a function using a STOKE cost function"
@@ -108,13 +112,9 @@ then
 elif [ "$SCMD" == "testcase" ]
 then
 	$HERE/stoke_testcase "$@"
-elif [ "$SCMD" == "database" ]
-then
-	$HERE/stoke_database "$@"
 elif [ "$SCMD" == "test" ]
 then
 	$HERE/stoke_test "$@"
-
 else
 	echo "Unknown command: '"$SCMD"'"
 	echo "Type 'stoke --help' for usage."
